### ISSUE TITLE
ATTiny84 SPI

### ISSUE THREAD

**Issue by TCWORLD** [TCWORLD/ATTinyCore#25] opened 2014-08-30 10:03 UTC
_This has been moved from another issue as it was unrelated_

> Hi Guys
>  I love this atuo SPI thing and currently have it working with RF24 library and NRF modules but am really battling to get it working with ATTINY84 ... I'm not sure how the pin mappings work . I have wired according to variants and various other combinations.
>  I there a walk-through and perhaps a pin mapping config I could check/change to get it working please ?
>  Tom I have emailed you but have had no response. Is there a way to contact you to discuss this issue ?
>  Regards
>  Den

**Comment by TCWORLD** [comment] 2014-08-30 10:21
I have already pointed you to the folder in which all of the pin definitions are located, but as they seem to be hard to find, the pin mappings are [here at line 113](https://github.com/TCWORLD/ATTinyCore/blob/master/tiny/cores/tiny/TinySoftwareSPI.h) and the default SPI pin numbers are [at line 39](https://github.com/TCWORLD/ATTinyCore/blob/master/tiny/cores/tiny/TinySoftwareSPI.h)

Furthermore, those are just one option. The software SPI master library included in this core can use any pins which are defined by using this function instead of the normal begin():

``` C++
void begin(byte SCK_, byte MOSI_, byte MISO_, byte SS_); 
```

**Comment by den4444** [comment] 2014-09-04 02:01
Hi again Tom 
Thanks for you reply I really appreciate it. :-)
Sadly I am not quite sure where I am going wrong in trying to get this to work.
I am using the RF24 maniac bug library for arduino to use an NRF24L01+ radio module.
(the other libraries that exist for these are MIRF and RADIOHEAD)
I have attached an image of the beginning of my arduino code (see the arduino code window snippet image below) which I am trying to get working on the ATTINY84.
The code compiles fine but I think I have the wrong pins connecting to my radio and don't know which ones to match or set in the code or what pins they match to in spi :-(
As you can see I don't do an #include to your library ...is this correct ?
Should I be adding something like spi.begin() ?
I am also really not sure how I need to implement or manipulate this line that you mentioned.
void begin(byte SCK_, byte MOSI_, byte MISO_, byte SS_); 
If you could please assist me I will be most grateful.
And I would also be more than happy to help test your core on the chips I have.
i look forward to your reply.
If you need more info please let me know.
![no line 113](https://cloud.githubusercontent.com/assets/8570263/4144020/c4261d9e-33d6-11e4-8a1d-80b0356484e1.JPG)
![line 39](https://cloud.githubusercontent.com/assets/8570263/4144024/d3033d10-33d6-11e4-8684-38f97bb5b26d.JPG)
![rf spi problem](https://cloud.githubusercontent.com/assets/8570263/4144041/18d1d13a-33d7-11e4-9e76-e17329e4a3ad.JPG)

Kind regards
Den

Please see attached image .. am I missing something re line 113 ...the link only shows 83 lines ?

**Comment by TCWORLD** [comment] 2014-09-04 09:30
Hi Den, I've corrected the links in my previous post, should make more sense now.

To use that library, you'll need to change line 23 of the RF24_config.h file to

``` C++
 #include <TinySoftwareSPI.h>
```

If you want to change the library to use different pins, edit line 340 of RF24.cpp such that it calls the correct begin function as I specified earlier, such as:
SPI.begin(1,2,5,4); //use pins 1,2,5,4 for SPI - could use any, just picked some at random.

**Comment by den4444** [comment] 2014-09-04 10:42
Hi Tom
Thank you so much :-) you are a scholar and a gentleman. 
I will give this a bash and ping you back with results. 
I must apologize though for messing you around , in my confusion and excitement and frustration to try get things working on both an ATTINY85 (which I have had success with, and and now an ATTINY84 (which is where I am battling and stumbling along in the dark), I actually realized/remembered that I am working with a forked library here https://github.com/TMRh20
and the rf24_config.h is here
https://github.com/TMRh20/RF24/blob/master/RF24_config.h
So is this where the problem could be ? 
I'm not sure where to pop the defines in on this https://github.com/TMRh20/RF24/blob/master/RF24_config.h
I decided to try this forked library as TMRh20 seems to be doing some great work with the NRF24 modules and voice ..check his blog here http://tmrh20.blogspot.com/
As regards this comment "SPI.begin(1,2,5,4); //use pins 1,2,5,4 for SPI - could use any, just picked some at random."
Should I use each pin as listed in the attinycore for an attiny84 or is it as you say any pin can be anything ?
And I assume I would be changing this line 
https://github.com/TMRh20/RF24/blob/master/RF24.cpp
to something like this
SPI.begin(1,2,5,4); //use pins 1,2,5,4 for SPI 
and then can you confirm I should be using the DIGITAL pin defines like this for example  D5 (PA5) is physical pin 8 ...
So is it correct to refer to it as 5 in the code ?

// ATMEL ATTINY84 / ARDUINO
//
//                                          +-\/-+
//                                VCC  1|    |14  GND
//                      (D  0)  PB0  2|    |13  AREF (D 10)
//                      (D  1)  PB1  3|    |12  PA1  (D  9) 
//                                 PB3  4|    |11  PA2  (D  8) 
//   PWM  INT0  (D  2)  PB2  5|    |10  PA3  (D  7) 
//      PWM        (D  3)  PA7  6|    |9   PA4  (D  6) 
//      PWM        (D  4)  PA6  7|    |8   PA5  (D  5)        PWM
//                                          +----+

Once again thank you very much for your reply and assistance and look forward to your reply.

Kind regards
Den

**Comment by TCWORLD** [comment] 2014-09-04 11:48
Grr, githubs markdown parsing buggered up part of my last post, but I've now corrected it.
Actually, adding something like this in place of line 31 of the file you posted a link to (RF24_config.h) would be better:

``` C++
#ifdef USE_SOFTWARE_SPI
 #include <TinySoftwareSPI.h>
#else
 #include <SPI.h>
#endif
```

That way it will automatically swap in the software SPI for chips which don't have the hardware one.

Also, you should delete lines 104 to 147 from that file as they are not needed with the addition of the above #include.

**Comment by den4444** [comment] 2014-09-04 11:57
LOL @ github !! GRR too and sorry!
Ooops i just updated my post to clear up further confusion and show/give you more details :-) Please check last post from me

**Comment by den4444** [comment] 2014-09-04 12:04
Tom ..
What about adding a fork for that and including it in your github :-) I'm sure you will get many more hits too.
Your core certainly does solves a lot of the confusion around this dark mystery regarding SPI and the ATTINY cores.
I also certainly think it will be most welcomed across the globe :-)
this certainly is helping me clear up some confusion as there there are few posts and pages on the web which actually explain the linking of the SPI library with the code on implements and/or how to do it.
Particularly the PIN confusion which is even more confusing for newbies in this space.
Oh and just to firm the change you refer to on line 31 in rf_config.h
here are lines 30 and 31 as per github numbering ..can you confirm they are correct ?
#if defined (ARDUINO) && !defined (**arm**)
#include <SPI.h>
And i should be replacing the line
#include <SPI.h>
with

#ifdef USE_SOFTWARE_SPI
 #include <TinySoftwareSPI.h>
#else
 #include <SPI.h>
#endif

Thanks again
Den

**Comment by jeffmurchison** [comment] 2014-09-04 12:40
@den4444 I've been able to use the nRF24l01+ modules with an ATtiny84 and TMRh20's libraries without modifying them. The example code works almost out of the box - you just need to modify a couple lines (mainly: removing serial, the SPI.h include, and the SPI.begin line).

If you're having trouble finding out which pin is which on the ATtiny84, use the following reference sheet: 

http://www.akafugu.jp/images/microcontroller-reference-sheet.png

Just note that for some reason, on the ATtiny24/44/84 diagram, they're missing MOSI which should be on pin 7. As for pins on the nRF24l01+ module:

http://murchlabs.com/wp-content/uploads/2013/07/RF240131.jpg

And in your code, when you have the line "RF24 radio(X,Y);" remember that X is the digital pin you have CE connected to and Y is pin you have CSN connected to. 

Hope that helps.

**Comment by den4444** [comment] 2014-09-04 18:38
Hey Jeff :-)

Thanks a million for the tips :-)
Is this a kind of paradox ? "without modifying them.you just need to modify a couple lines .."

Can you elaborate regarding this line you mentioned ?
"you just need to modify a couple lines (mainly: removing serial, the SPI.h include, and the SPI.begin line)." 
All a little SKETCHy so to speak :-) (as in Arduino SKETCH hehehe)
I too tried TMRh20 code "out of the box" with ATTINY84 with no result and also contacted him, got a reply back saying "As I said previously, the ATTiny info is found here http://tmrh20.github.io/RF24/  including the pin info. Please keep in mind that beyond the countless days of programming, documenting and working to improve the libraries, I do not offer a technical support service as well, since this is open source software."

WOW all I asked for was a little help getting started with the library.
And so I am eternally grateful to Tom and now you Jeff for the help.
I too have had many countless hours of trying to grasp concepts code and clear up the confusion surrounding thsi very topic of the core and amongst other things the CORES out there.
Because if the core is rotten the foundation is.
And this line you mention is where all the confusion begins
"If you're having trouble finding out which pin is which on the ATtiny84, use the following reference sheet: "
Well those datasheets are where the problems stem from with odd info about mosi miso etc.
And to compound to the problem people just say "oh yes just connect PIN X to Y!"
And then the confusion snowballs.
Because Like you mention "they're missing MOSI which should be on pin 7"
Jeff thanks for the diagrams :-) 
I already have checked those out too, and have the ATTINY85 running with the NRF24L01+ and TC's library , my problem has been the ATTINY84.
Just a quick question to you ... would you care to present a pin to pin mapping perhaps?
Check the excel screen cap of mine attached here.
![nrf to Atmel](https://cloud.githubusercontent.com/assets/8570263/4154656/94f54756-3463-11e4-816a-58f24885ac42.JPG)
I am still busy solving the ATTINY84 issue so don't take that as gospel yet :-)
Hope it helps someone and add's to TC's world so far.

In code people refer to PIN X as a physical pin while others refer to a DIGITAL PIN and still other refer to an ANALOG PIN.
Then the core's may have different pin mappings to the sketch/program and vice versa. And there are few sites that I have seen where there is an actual wiring schematic with complimentary code and working examples.
The people generally just say .. hey just grab my code on GITHUB where i forked from the main library made a couple of changes (more often than not not clearly documented - I mean let's face it a single value/letter change is a change and a version update not so ?)
So you generally have a mismatch starting with the hardware, moving to the code and then even up as far as compiler and eventually application.
Sad that there is no common platform or pluggable layer or API.
And wow switching from one type of in out to another and yet another like char int bin dec etc, It took me a rather long time to just get to send 18 bytes in one form or another from one place to another..i.e loading the payload or package.
So hats off to Tom's core which I think is adaptable it seems.
And thanks again Jeff for the pointers :-).. I will try them.
Den

**Comment by den4444** [comment] 2014-09-04 21:57
OK !!
@ Tom as excited as I am to get this working there is still confusion about all the (now possible) changes :-).. I am just busy trying it now. 
Are these the steps and files etc.
1. 
   I would like to achieve a working TCCore and RF24 library.
   Here are the pinouts as per datasheets (I think --unless I read a different datasheet on the net)
   CE   5  /D2
   CS   6  /D3
   SCK  9  /D6
   MOSI 7 /D4
   MISO 8  /D5

Now according to your first post , you said "The software SPI master library included in this core can use any pins which are defined by using this function instead of the normal begin():

void begin(byte SCK_, byte MOSI_, byte MISO_, byte SS_); "

That's great but where is the NORMAL BEGIN ? 
Is it in the arduino code sketch ? 
So in other words where do I state that 
byte SCK_ = 9 or is it D6 or is it just 6  ??
byte MOSI_
byte MISO_
byte SS_
And is this 6 as in D6 or 9 as in chip pin 9 ?
Are both the core and the RF library using the same pins (as in digital or chip pin) ?

And according to first and earlier posts you mention line numbers in files but there is a line number mismatch too..are you using the default github viewer with line numbers on the left too ?

Can you confirm if I must still make changes here too ?
 to the RF24.cpp file @ line 340 ...  these are actually @ line 430. hehehe had me going!
 // Initialize pins
pinMode(ce_pin,OUTPUT);
#if defined(**arm**) && ! defined( CORE_TEENSY )
SPI.begin(csn_pin); // Using the extended SPI features of the DUE
SPI.setClockDivider(csn_pin, 9); // Set the bus speed to 8.4mhz on Due
SPI.setBitOrder(csn_pin,MSBFIRST);  // Set the bit order and mode specific to this device
SPI.setDataMode(csn_pin,SPI_MODE0);
ce(LOW);
//csn(HIGH);

and I did this 
"Actually, adding something like this in place of line 31 of the file you posted a link to (RF24_config.h) would be better:

#ifdef USE_SOFTWARE_SPI
 #include <TinySoftwareSPI.h>
#else
 #include<SPI.h>
#endif
"
Oh and now did I have to have imported your library as TinySoftware_SPI and named it such during the import ?

And I don't think I should be deleting lines 140 onwards 'cos I'm not sure the lines numbers are correct :-(

AAAAARGH 
I am now totally entirely bamboozled ...I actually don't know whether to laugh or cry :-( :-) ???

Den

**Comment by den4444** [comment] 2014-09-04 22:04
Can we please just start again ?
1.
I would like to use the AWESOME TCCore (which has innovative features like AUTO-SPI)
to program an ATTINY84 with the following pin assignments 
CE 5 /D2 
CS 6 /D3 
SCK 9 /D6 
MOSI 7 /D4 
MISO 8 /D5
(or ones you suggest for CE and CS , SCK ,MOSI,MISO)
 to support the 
2. 
TMRh20 RF library (which is a fork of the maniacbug RF24 library)
3.
Connecting to a NRF24L01+ radio module

What do I need to change to make this happen and where ? 
Please bear in mind the line numbers dont seem to match here @ github (is it just us ?)

10 goto 20
Abort,retry,fail ? 
 20 goto 10 ? 

Kind regards 
Den

**Comment by den4444** [comment] 2014-09-04 23:07
Ok I think I may finally be getting somewhere..(or not?)
I made these changes at line 31 of RFconfig_h
#ifdef USE_SOFTWARE_SPI
 #include <TinySoftwareSPI.h>
#else
 #include <SPI.h>
#endif

AND THEN 
in the RF24.cpp file at about line 440 I added this line - my pin declarations for SPI
SPI.begin(6,4,5,3); //use pins 1,2,5,4 for SPI - could use any, just picked some at random
then using arduino 1.05r2 windows version and arduino as an ISP to program the ATTINY84@8MHZ no bsd (based on TCCore offering.

I receive these compile errors from arduino IDE

In file included from C:\Users\d\Documents\Arduino\libraries\RF24/RF24.h:18,
                 from dennrf24l01txrx1working84.ino:2:
C:\Users\d\Documents\Arduino\libraries\RF24/RF24_config.h:150: error: conflicting declaration 'SPIClass SPI'
C:\Program Files (x86)\Arduino\hardware\tiny\cores\tiny/TinySoftwareSPI.h:81: error: 'SPI' has a previous declaration as 'SoftSPIClass SPI'

**Comment by den4444** [comment] 2014-09-05 00:39
OK an update :-)
with only this change 
SPI.begin(6,4,5,3); //use pins 1,2,5,4 for SPI - could use any, just picked some at random
in file RF24.cpp
the errors are ...
C:\Users\d\Documents\Arduino\libraries\RF24\RF24.cpp: In member function 'void RF24::begin()':
C:\Users\d\Documents\Arduino\libraries\RF24\RF24.cpp:443: error: no matching function for call to 'SPIClass::begin(int, int, int, int)'
C:\Users\d\Documents\Arduino\libraries\RF24\/RF24_config.h:138: note: candidates are: static void SPIClass::begin()

So it seems and SPIClass definition :-) I think this was added to this fork by JSCrane as a universal SPI offering.

**Comment by jeffmurchison** [comment] 2014-09-05 01:51
(Edit: corrected a small mistake in the pin connections)

I'm not sure why you're modifying the libraries, they should work just fine as they are. Re-install the RF24 and RF24Network libraries from TMRh20 to undo any changes you made.

In my example here I'll use an Arduino Uno and an ATtiny84, and we'll only use example code that's included with the libraries to make it easy. Because the code is a bit simpler, I'm going to use example code from the RF24Network library to get you started.

First, we'll hook up the nRF24l01+ transceivers. On the Arduino, make the following connections 

| Transceiver pin | Arduino Pin |
| :-: | --- |
| GND | GND |
| VCC | 3.3v |
| CE | D9 |
| CSN | D10 |
| SCK | D13 |
| MOSI | D11 |
| MISO | D12 |

Now connect the transceiver to the ATtiny84 as follows:

| Transceiver pin | ATtiny84 Pin |
| :-: | --- |
| GND | GND |
| VCC | 3.3v |
| CE | Pin 12 / D9 |
| CSN | Pin 13 / D10 |
| SCK | Pin 9 / D6 |
| MOSI | Pin 8 / D5 |
| MISO | Pin 7 / D4 |

Now for the ATtiny84 it doesn't have to be 3.3v, I just chose that because it's fairly common. Just make sure that it's around 3v and no more than 3.6v or you may fry the transceiver.

Load up the example code for the ATtiny84. In the Arduino IDE, go to File > Examples > RF24Network and select "helloworld_rx." Now we need to make a few changes. We basically just want to remove all the Serial and SPI references as they're not supported on the ATtiny. Remove the following lines:

```
(line 20) #include <SPI.h>

(line 37) Serial.begin(57600);

(line 38) Serial.println("RF24Network/examples/helloworld_tx/");

(line 40) SPI.begin();
```

and the following chunk of code (lines 55-58):

```
Serial.print("Received packet #");
Serial.print(payload.counter);
Serial.print(" at ");
Serial.println(payload.ms);
```

With the ATtiny84 @ 8MHz board selected under Tools > Board, it should compile just fine. You can go ahead and upload that to your ATtiny84.

Now for the Arduino code. Just load up the "helloworld_tx" example under the same directory as before. It should be fine as is, so go ahead and upload that to the Arduino Uno. 

You should open your serial monitor and change the baud rate to 57600. When both units are powered, the Arduino will transmit a packet to the ATtiny, which will return it, and you should see it in the serial monitor.

Hope that helps.

**Comment by TCWORLD** [comment] 2014-09-05 07:28
I'll summarise again:
In RF24_config.h replace line 31 with:

``` C++
#ifdef USE_SOFTWARE_SPI
 #include <TinySoftwareSPI.h>
#else
 #include <SPI.h>
#endif
```

Then, from the same file, remove lines 104 to 147 (#if defined **AVR_ATtiny25** ... to #endif).

You'll also have to remove lines 1279 to 1327 from RF24.cpp to remove the hacked SPI class that is getting added and causing the duplication errors. Those are indeed the line numbers github uses.

All the pin numbers I am quoting are 'Digital Pin' numbers, i.e. like an Arduino. It seems to be the norm to use this for anything Arduino related. The pins_arduino.h file has the mappings in - there is an ascii drawing of it.

---

Jeff, I think the idea here is to get the library working with this core - which already includes an SPI class which switches in software support for SPI.

**Comment by den4444** [comment] 2014-09-05 12:43
Hi Jeff/Tom
WOW thank you so much for the replies and assistance.
@Tom you are 100% correct !.. a core that includes an auto-SPI that is easily adaptable across libraries :-) What made me delve into this was the fact that I was running virtualwire libraries on my little radio modules @ 433MHZ and the code was working on ATTINY85's with attiny-core.
then virtualwire library changed to become Radiohead. All fine and well and my code using the Radiohead libraries for 433MHZ still works great! 
Problem was that the radio modules were very sensitive to noise and I decided to purchase a few NRF24L01+ modules.
While RadioHead libraries do support these, they are not fully supported for the ATTINYX operation and NRF24L01. You can see my posting under the ATTINY85 forum there where I was told it might be possible to get their libraries working on the ATTINY85 provided they supported SPI in some way or another. An I know they do but with software implementation.
So I checked out the maniacbug libraries which apparently do support this and some people globally have writteen a few blogs about how they got SPI working with the ATTINY84 (which I have yet to get working !!) 
That was not what I was looking for at the time since I was after the same thing but for an ATTINY85 and for ATTINY to work as a receiver, unlike almost every other post where they are transmitters. 
I also needed a free pin after all code was working and implemented, and this meant utilizing the reset pin on the ATTINY85 (This is managed and all works great - thanks to the TCworld core which I was introduced to by going through TMRh20's RF24 forks)
It has been nearly 4 months or more using any spare time I have and late nights sifting through the various sites and blogs, datasheets and more just to get that all done.
I would like to state formally that it would be awesome TOM if your core could easily adapt to all of the main NRF24L01 libraries (and anything spi related in fact ;) and I would be more than happy to test the functionality for you on the kit I have too:-)
I also suggest possible touching base with Mike @ radiohead and perhaps create links back and forth perhaps .. as there is some great progress being made there in the radio space ..WOW.

@ Jeff ... THANK YOU !
I will go through te steps steps by step and meticuolousy and try to get it going :-) 
It has been driving me nuts to try to get the ATTINY84 working with these modules! 
As stated earlier(or did I?) I have them working perfectly with the Arduino UNO and the ATTINY85 but the '84's are really just not coming to the party !!
I have tried different code, cores, pins , radio modules checked and double checked wiring and drank lots of coffee too!
Maybe I have missed something like calibration of fuses or something ...
Maybe something really basic like prescaler setting or burning a bootloaded ? What do you maybe suggest I check 'cos this really has me stumped!

Do you (or anyone else reading this ) know of some led blinking implementation I could use to test that SPI is indeed doing its thing as I dont have the luxury of a proper logic analyser to test it with.
I keep thinking it must be eirther the library or core where my problem lies.
I can upload code to blink LED's on and off to the 84 by using the TCcore and have tested all the digital pins by blinking and led on the digital pins. And my code uploads just fine onto the 84. But lo and behold there is no receiving of the data the NRF radio should be sending. If I take this code and move it to another ARDUINO it works like a charm!!
So (arduino + nrf) to (arduino +nrf)  all's good !
AND (ATTINY85 + nrf) to (arduino+nrf )all good
BUT (ATTINY84 + nrf) to (arduino + nrf) no go !!

So Jeff I will follow your steps and re-wire the ATTINY84 , I will first test between arduinos and then  i will try from the 84 and let you know the result!
Who knows maybe the default helloworld works.
Whatever works I will be thrilled indeed!
Perhaps i could ask you to run demo the code I have as a test too ?

@ Tom and Jeff 
Ultimately one shouldn't have to be dependent on a particual library and module(like a forked spi for example) .. it should all just be pluggable don't you think ?
I mean hey , I should be able to just make the changes Jeff suggests and wham I'm in business right ?

Look forward to your replies.

kind regards 

Den

**Comment by den4444** [comment] 2014-09-05 13:58
@jeff 
Hey Jeff 
Tried your steps to a T 
All works fine between Arduinos
But arduino and 84 ..doesn't work !! eeek
I followed your steps for the 84, all pin connections followed to a T for ce,cs,miso,mosi and SCK (the only differences between your example and my existing were CE and CS) and also just added an LED routine both in the receive loop and just before because I dont have serial on the attiny 84 for those serial.print lines (and commented them out)
the main loop is runningfine and led blinkin but the inner loop where the serial.prints were and where the the radio.read is where the problem seems to be.
I will check all soldered joints and pins from chip to radio on my stripboard and move it all back to bread too later. this is really UNCANNY !! 
I have swapped radio modules and it does the same so its not them ..they are working fine.
the only think I have not changed is the 84 and/or the board it's on. I hope this isn't a chip or wiring issue ! EEK

Will update as we go!

@Tom 
Will try your updates and post result here asap.
Stay tuned 

Den

**Comment by den4444** [comment] 2014-09-05 15:09
@Jeff and @Tom 
Using the Helloworld_rx code on the ATTINY84
I have now replaced the ATTINY84 and still same issue ...next step is off the stripboard back to a breadboard.
Just wondering if this could be a fuse problem or some sort of library issue ?
@Jeff 
What core and what version of arduino are you using ?
I have ZERO errors on compiling by the way !

Kind regards
Den

**Comment by den4444** [comment] 2014-09-05 15:12
@Jeff and/or Tom 
here's the code if you would like to load and check ;)
#include <RF24Network.h>
#include <RF24.h>
//#include <SPI.h>

RF24 radio(9,10);                // nRF24L01(+) radio attached using Getting Started board 

RF24Network network(radio);      // Network uses that radio
const uint16_t this_node = 00;    // Address of our node in Octal format ( 04,031, etc)
const uint16_t other_node = 01;   // Address of the other node in Octal format

struct payload_t {                 // Structure of our payload
  unsigned long ms;
  unsigned long counter;
};

void setup(void)
{
  pinMode(1,OUTPUT);
  //Serial.begin(57600);
  //Serial.println("RF24Network/examples/helloworld_rx/");

  //SPI.begin();
  radio.begin();
  network.begin(/_channel_/ 90, /_node address_/ this_node);
}

void loop(void){
     digitalWrite(1, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);               // wait for a second
  digitalWrite(1, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);

  network.update();                  // Check the network regularly

  while ( network.available() ) {     // Is there anything ready for us?

```
RF24NetworkHeader header;        // If so, grab it and print it out
payload_t payload;
network.read(header,&payload,sizeof(payload));

//Serial.print("Received packet #");
//Serial.print(payload.counter);
//Serial.print(" at ");
//Serial.println(payload.ms);
digitalWrite(1, HIGH);   // turn the LED on (HIGH is the voltage level)
```

  delay(400);               // wait for a second
  digitalWrite(1, LOW);    // turn the LED off by making the voltage LOW
  delay(400); 
digitalWrite(1, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(400);               // wait for a second
  digitalWrite(1, LOW);    // turn the LED off by making the voltage LOW
  delay(400);  
}
}

**Comment by den4444** [comment] 2014-09-06 01:09
@TCWORLD 
@jeffmurchison 
Hi guys 
SUCCESS !! YAAAAAAAY
OK heres the story.
@jeff I thought I would give your setup a bash even though I had that working before on arduinos and the ATTINY85 and was going crazy not knowing why it wasnt working on the ATTIY84.
so after following your walk-through step by step and it still wasn't working I decided it must be the ATTINY84. So I swopped it out (see previous posts) that didn't work either.
So i thought it must either be a software issue (wanted to immediately think it was the core again and my pin mappings 
OR 
Hardware .. 
So i decided to pop another copy of my circuit onto breadboard. I connected the same was as Jeff pointed out (since he said it was working for him) and switched on !
Damn ... no joy.
then I remembered something that I have seen in a few articles and have been doing quite often in my tests and that is MOSI and MISO for some reason get switched around and may even be incorrectly labelled in the main docs for ATTINY84. Don't know if the blogs I read are correct but I decided to try it anyway and ...
WHAM IT WORKED ..wireless packets were flying back and forth and LED's flashing like crazy.
So the problem I think (still to be confirmed) is somewhere on the stripboard shield I made. I suspect it's a dry joint or bad wiring 'cos I decided to use thin trackwire which I don't normally do. Also I generally build on breadboard first but for some reason this time I didn't.
So now that it was working I could eliminate the thoughts of bad hardware issues.
thanks a million Jeff for the clear pin-outs and walk-thru...you motivated me to go back to square 0000001.
Now it was time to give Tom's code changes a bash :-)
@Tom 
WOW ..your SPI detection and core works like a bomb...YAY.
I can confirm the changes you suggest work perfectly for the TMRh20 library. And work perfectly well for the original maniacbug RF24 library too. :-)
I haven't had a chance to test the RF@network libraries yet .. do you have any ticks for that one too ?
I decided I should actually go back and test the RADIOHEAD library too. 
Well I have and have found compile errors which I will post tomorrow but only if you have an interest in being compatible with the RADIOHEAD library too. So let me know and I can test for you :-)
By the way ..
When using TCcore and having made those changes in the RH_config.h file and the .cpp file , when you are using an ATTINY you don't have to #include SPI.
However if you are using an arduino UNO (which I am using as the receiver) like I am then you have to specify the #include <SPI.h> line .
I assume this is becuase arduino the bigger chips have SPI hardware 
BUT ...
should there be an autodetect happening and you shouldn't have to include SPI in your code ?
With radio head I poked around in the client example for NRF24 and changed the #def lines like Tom mentioned for the RFconfig.h file howere when I try compile the arduino IDE compiler generates the following errors/issues..
C:\Users\d\Documents\Arduino\libraries\RadioHead\RH_ASK.cpp: In member function 'void RH_ASK::timerSetup()':
C:\Users\d\Documents\Arduino\libraries\RadioHead\RH_ASK.cpp:192: error: 'TIMSK' was not declared in this scope
@tom for your reference the file is here :+1: and the library and docs are here (perhaps chat to Mike if you'd like to make your CORE compatible and vice versa ?
http://www.airspayce.com/mikem/arduino/RadioHead/nrf24_client_8pde-example.html
Thats the file ..it's the client and there is a server or it under the examples tab at the main site
And here's the main site url 
http://www.airspayce.com/mikem/arduino/RadioHead/index.html

And that's all for now ;))

Kind regards 

Thanks a million to both @Tom and @Jeff ..You guys are legends :-)

Den

**Comment by TCWORLD** [comment] 2014-09-06 16:23
TIMSK is a hardware register related to timers which means the RadioHead library will need updating to work with the the timers of the attiny84. Your best bet is to change the code to have #if defined statements to check the processor.

Tom

----- Reply message -----

**Comment by jeffmurchison** [comment] 2014-09-06 18:25
@den4444 Ah yes, my apologies, I totally knew that MISO / MOSI were switched I just forgot. Glad to see you got it working. I've edited my post above.

**Comment by den4444** [comment] 2014-09-19 19:23
@TCWORLD and @jeffmurchison 
Once again thank you very very much for your help :-) it really was the light in a very dark tunnel.
Kind regards
Den

**Closed as completed** 2014-12-15 19:50 UTC

**Comment by Raynman77** [comment] 2016-04-02 23:42
@jeffmurchison I know this issue was closed, but I was following your suggestions on a hello_world_tx on the arduino and hello_world_rx on an ATTiny84. I wanted to do this in reverse order so I removed all serial stuff from the ATTiny hello_world_tx and loaded it up. Then left the arduino hello_world_rx as is. It is not working. Any suggestions would be greatly appreciated. I've been smashing my face in for days now.
